apiVersion: v1
kind: Service
metadata:
  name: busca-clase-opensearch1-service
spec:
  selector:
    app: opensearch-node1
  ports:
  - protocol: "TCP"
    port: 9200
    targetPort: 9200
  type: LoadBalancer


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: opensearch-node1


spec:
  selector:
    matchLabels:
      app: opensearch-node1
  replicas: 1
  template:
    metadata:
      labels:
        app: opensearch-node1
    spec:
      containers:
      - name: opensearch-node1
        image: opensearchproject/opensearch:latest
        imagePullPolicy: Never
        env:
          - name: cluster.name
            value: opensearch-cluster
          - name: node.name
            value: opensearch_node1
          - name: discovery.seed_hosts
            value: opensearch_node1,opensearch_node2
          - name: cluster.initial_cluster_manager_nodes
            value: opensearch_node1,opensearch_node2
          - name: bootstrap.memory_lock
            value: "true" # along with the memlock settings below, disables swapping
        ports:
        - containerPort: 9200
