x-dash-no-sec: &dash-no-sec
  context: ./
  dockerfile: ./opensearchDocker/Dockerfile

version: '3'

services:

  opensearch_node1:
    image: opensearchproject/opensearch:latest
    container_name: opensearch_node1
    environment:
      - cluster.name=opensearch-cluster
      - node.name=opensearch_node1
      - discovery.seed_hosts=opensearch_node1,opensearch_node2
      - cluster.initial_cluster_manager_nodes=opensearch_node1,opensearch_node2
      - bootstrap.memory_lock=true # along with the memlock settings below, disables swapping
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m" # minimum and maximum Java heap size, recommend setting both to 50% of system RAM
      - "DISABLE_SECURITY_PLUGIN=true"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536 # maximum number of open files for the OpenSearch user, set to at least 65536 on modern systems
        hard: 65536
    volumes:
      - opensearch-data1:/usr/share/opensearch/data
    ports:
      - 9200:9200
      - 9600:9600 # required for Performance Analyzer
    networks:
      - opensearch-net

  opensearch_node2:
    image: opensearchproject/opensearch:latest
    container_name: opensearch_node2
    environment:
      - cluster.name=opensearch-cluster
      - node.name=opensearch_node2
      - discovery.seed_hosts=opensearch_node1,opensearch_node2
      - cluster.initial_cluster_manager_nodes=opensearch_node1,opensearch_node2
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
      - "DISABLE_SECURITY_PLUGIN=true"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - opensearch-data2:/usr/share/opensearch/data
    networks:
      - opensearch-net

  opensearch-dashboards:
    #image: opensearch-dashboards-no-security
    build: *dash-no-sec
    container_name: opensearch-dashboards
    ports:
      - 5601:5601
    expose:
      - "5601"
    environment:
      OPENSEARCH_USERNAME: admin
      OPENSEARCH_PASSWORD: admin
      DISABLE_SECURITY_PLUGIN: true
      OPENSEARCH_HOSTS: '["http://opensearch_node1:9200","http://opensearch_node2:9200"]'
    networks:
      - opensearch-net

  web:
    image: opensearchproject/web:latest
    build: .
    ports:
      - "5000:5000"
    networks:
      - opensearch-net

volumes:
  opensearch-data1:
  opensearch-data2:


networks:
  opensearch-net: